// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:eco_earth/secrets.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: API_KEY_WEB,
    appId: APP_ID_WEB,
    messagingSenderId: MESSAGING_SENDER_ID,
    projectId: PROJECT_ID,
    authDomain: AUTH_DOMAIN,
    storageBucket: STORAGE_BUCKET,
    measurementId: MEASUREMENT_ID,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: API_KEY_ANDROID,
    appId: APP_ID_ANDROID,
    messagingSenderId: MESSAGING_SENDER_ID,
    projectId: PROJECT_ID,
    storageBucket: STORAGE_BUCKET,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: API_KEY_IOS,
    appId: APP_ID_IOS,
    messagingSenderId: MESSAGING_SENDER_ID,
    projectId: PROJECT_ID,
    storageBucket: STORAGE_BUCKET,
    iosBundleId: IOS_BUNDLE_ID,
  );
}
